version: '3.7'
services:
  db:
    image: postgres:9.6.17-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: lotr
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  populate:
    build: ./lotr-populate-db/.
    depends_on:
      - db
    links:
      - db

  api:
    build: ./lotr-api/.
    ports:
      - '8081:8081'
    depends_on:
      - db
      - populate
    links:
      - db

  frontend-dev:
    build:
      context: ./lotr-frontend/.
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    environment:
      API_URL: api
    volumes:
      - /app/node_modules
      - ./lotr-frontend:/app

  frontend-prod:
    build:
      context: ./lotr-frontend/.
      dockerfile: Dockerfile.prod
    ports:
      - '3000:80'
    environment:
      API_URL: api
